language: python
python:
  - 3.2
  - 3.3
  - 3.4

env:
  - OWNCLOUD=7 BRANCH=stable7
  - OWNCLOUD=8 BRANCH=stable8
  - OWNCLOUD=8.1 BRANCH=master

before_install:
  - sudo add-apt-repository ppa:ondrej/php5-oldstable -y
  - sudo apt-get update

install:
  # use older pip version if on python 3.2 to prevent breakage
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install jinja2==2.6; fi
  # install the lib
  - pip install setuptools
  - python setup.py install
  # install phpunit and php
  - sudo apt-get update
  - sudo apt-get install php5
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit

before_script:
  # setup owncloud
  - cd ../
  - ocdev setup core --branch $BRANCH
  - cd core/apps
  - ocdev startapp --email test --author test --owncloud $OWNCLOUD MyApp
  - cd myapp

script:
  - phpunit tests
  - cd ../../../ocdev
  - python3 setup.py test

